-- 코드를 입력하세요
SELECT CRCR.CAR_ID, CRCR.CAR_TYPE, ROUND(CRCR.DAILY_FEE*30*(100-CRCDP.DISCOUNT_RATE)/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCR LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    ON CRCR.CAR_ID = CRCRH.CAR_ID AND CRCRH.START_DATE <= '2022-11-30' AND CRCRH.END_DATE >= '2022-11-01'
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CRCR.CAR_TYPE = CRCDP.CAR_TYPE AND CRCDP.DURATION_TYPE = '30일 이상'
WHERE CRCRH.CAR_ID IS NULL
HAVING FEE BETWEEN 500000 AND 2000000