-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, UI.GENDER, COUNT(DISTINCT(UI.USER_ID)) USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER