-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, COUNT(DISTINCT(UI.USER_ID)) PURCHASED_USERS,
ROUND(COUNT(DISTINCT(UI.USER_ID))/(SELECT COUNT(*) AS USER_COUNT
FROM USER_INFO UI
WHERE YEAR(UI.JOINED) = '2021'),1) PURCHASED_RATIO
FROM USER_INFO UI JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
    WHERE YEAR(UI.JOINED) = "2021"
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)