-- 코드를 입력하세요
SELECT CRH.HISTORY_ID, ROUND((C.DAILY_FEE * CRH.DATES)*(100-IFNULL(DP.DISCOUNT_RATE, 0))/100) AS FEE
FROM (SELECT CASE 
        WHEN DATEDIFF(CRH.END_DATE,CRH.START_DATE) +1 > 90 THEN "90일 이상"
        WHEN DATEDIFF(CRH.END_DATE,CRH.START_DATE) +1 > 30 THEN "30일 이상"
        WHEN DATEDIFF(CRH.END_DATE,CRH.START_DATE) +1 > 7 THEN "7일 이상"
        ELSE NULL
        END AS DISCOUNT_OPTION,
            CRH.CAR_ID, CRH.HISTORY_ID, DATEDIFF(CRH.END_DATE,CRH.START_DATE)+1 AS DATES
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH) CRH JOIN CAR_RENTAL_COMPANY_CAR C
    ON C.CAR_ID = CRH.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON DP.CAR_TYPE = C.CAR_TYPE AND DP.DURATION_TYPE = CRH.DISCOUNT_OPTION
WHERE C.CAR_TYPE = "트럭"
ORDER BY FEE DESC, CRH.HISTORY_ID DESC