-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    ON C.CAR_ID = CH.CAR_ID AND MONTH(CH.START_DATE) = "10"
WHERE C.CAR_TYPE = "세단"
ORDER BY C.CAR_ID DESC