-- 코드를 작성해주세요
WITH FE_CODE AS(SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End")

SELECT T.GRADE, T.ID, T.EMAIL
FROM (SELECT CASE
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') && D.SKILL_CODE & (SELECT CODE FROM FE_CODE))
        THEN 'A'
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))
        THEN 'B'
        WHEN (D.SKILL_CODE & (SELECT CODE FROM FE_CODE))
        THEN 'C'
        END AS GRADE, D.ID, D.EMAIL
FROM DEVELOPERS D) AS T
WHERE T.GRADE IS NOT NULL
ORDER BY T.GRADE, T.ID